---
kind: pipeline
type: docker
name: registry-latest-build

steps:
- name: docker-private-registry
  image: plugins/docker
  settings:
    repo: registry.jasonjero.me/jjmumblebotreworked
    registry: registry.jasonjero.me
    dockerfile: ./Dockerfile
    tags: ["${DRONE_BUILD_CREATED}-${DRONE_COMMIT_SHA:0:8}", "latest"]
    username:
      from_secret: registry_user
    password:
      from_secret: registry_secret
trigger:
  branch:
  - main
  event:
    include:
    - push
    exclude:
    - pull_request

---
kind: pipeline
type: docker
name: dockerhub-latest-build

steps:
- name: dockerhub-registry  
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_secret
    repo: jasonjerome/jjmumblebotreworked
    tags: ["${DRONE_BUILD_CREATED}-${DRONE_COMMIT_SHA:0:8}", "latest"]
trigger:
  branch:
  - main
  event:
    include:
    - push
    exclude:
    - pull_request
