kind: pipeline
type: docker
name: pytest-check
 
steps:
- name: pytest
  image: python:3.10
  commands:
  - pip install -r dev_requirements.txt
  - pytest

---
kind: pipeline
type: docker
name: registry-latest-build

steps:
- name: docker-private-registry
  image: plugins/docker
  settings:
    repo: registry.jasonjero.me/jjmumblebotreworked
    registry: registry.jasonjero.me
    dockerfile: ./Dockerfile
    tags: ["${DRONE_COMMIT_SHA:0:8}", "latest"]
    username:
      from_secret: registry_user
    password:
      from_secret: registry_secret
  when:
    event:
      include:
        - push
      exclude:
        - pull_request
---
kind: pipeline
type: docker
name: dockerhub-latest-build

steps:
- name: dockerhub-registry  
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_secret
    repo: jasonjerome/jjmumblebotreworked
    tags: ["${DRONE_COMMIT_SHA:0:8}", "latest"]
  when:
    event:
      include:
        - push
      exclude:
        - pull_request
- name: discord-notification-dockerhub
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from secret: discord_hook_id
    webhook_token:
      from_secret: discord_hook_token
    message: "New Commit Build - ${DRONE_COMMIT_SHA:0:8}\nPull: `docker pull jasonjerome/jjmumblebotreworked:${DRONE_COMMIT_SHA:0:8}`"
  depends_on:
  - dockerhub-registry
  when:
    event:
      include:
        - push
      exclude:
        - pull_request
