[tool.black]
line-length = 150
target_version = ['py38', 'py39', 'py310']

[tool.isort]
profile = "black"
line_length = 150

[tool.pytest.ini_options]
addopts = "-s -vv"
pythonpath = "."
testpaths = "tests"
required_plugins = ['pytest-randomly', 'pytest-timeout']
