### Main Settings ###
[settings.connection]
mute = true
deafen = true
register = false
comment = "Hi! I am Mumimo."
default_channel = ""
auto_reconnect = false
name = "Mumimo"

[settings.commands]
command_token = "!"
command_tick_rate = 0.1
max_multi_command_length = 200
max_command_queue_length = 500
command_history_length = 25

### Media Settings ###
[settings.media]
volume = 0.1
stereo_audio = true
max_queue_length = 50
ffmpeg_path = ""
vlc_path = ""
media_directory = ""

[settings.media.audio_ducking]
enable = false
volume = 0.05
threshold = 2500.0
delay = 1.0

[settings.media.youtube_dl]
proxy_url = ""
cookie_file = ""

### Plugin Settings ###
[settings.plugins]
plugins_path = "src/plugins/"
plugins_config_path = "config/plugins/"
custom_plugins_path = ""
disabled_plugins = []
safe_mode_plugins = []


### GUI Settings ###
[settings.gui]
enable = true
themes_path = "config/gui_theme.toml"
selected_theme = "dark"  # Default themes available: "light", "dark", "highcontrast"

[output.gui]
enable = true

[output.gui.canvas]
background_color = "black"
image_background_color = "black"
content_alignment = "center"
border = 0

[output.gui.text]
font = "Georgia"
standard_text_color = "Snow"
header_text_color = "red"
sub_header_text_color = "yellow"
index_text_color = "cyan"

### Database Settings ###
[settings.database]
# Database connection string format:
#   - dialect+driver://username:password@host/name
#   - dialect+driver:///host.db
# Database connection string examples:
#   - sqlite+aiosqlite://test:test@localhost:8000/mydatabase
# The database dialect, driver, username, password, host, and database name must be specified in an environment file if 'use_remote_database' is used.
use_remote_database = false
# If 'use_remote_database' is set to false, the 'local_database_path' must specify the full path of the database file.
local_database_path = "config/mumimo.sqlite"
local_database_dialect = "sqlite"
local_database_driver = "aiosqlite"

# Default permission groups format:
#     - default_permission_groups = [
#           "permission_group_1", 
#           "permission_group_2", 
#           ...
#       ]
# As shown in the example above, the default permission groups must be a list of strings.
# Each string represents the name of a permission group that can control user access to commands.
# Default values: ["none", "guest", "regular", "admin"]
# It is highly recommended not to remove the default permission groups, but feel free to add more.
default_permission_groups = ["none", "guest", "regular", "admin"]

# Default aliases format:
#     - default_aliases = [
#           ["myalias", "mycommand", "list,of,permission,groups"],
#           ...
#       ]
# As shown in the example above, each item must contain 4 elements:
#     1. Index 0: The name of the alias as a string value.
#     2. Index 1: The command that the alias should execute as a string value.
#     3. Index 2: The list of permission groups the alias belongs to as a comma-separated string value.
# Default values: Too long to list here, please check the wiki.
default_aliases = [ ["say", "echo", "guest,regular,admin"], ["quit", "exit", "guest,regular,admin"] ]
