[theme.light]
text_type = "header"
text_color = "black"
text_align = "center"

table_align = "center"
table_bg_color = "blanchedalmond"

row_align = "left"
row_bg_color = "blanchedalmond"


[theme.dark]
text_type = "header"
text_color = "yellow"
text_align = "center"

table_align = "center"
table_bg_color = "black"

row_align = "left"
row_bg_color = "black"

# Create custom themes here:
# Ensure all themes follow the naming scheme with 'theme.<my_theme_name>'
# Example: [theme.custom1]
