[output.file]
enable = true
level = "DEBUG"
path = "logs/"
format = "(%(asctime)s)[%(name)s][%(levelname)s]::%(message)s"
name = "mumimo_%s.log"
message_privacy = true
enable_stack_trace = false

[output.console]
format = "[%(levelname)s]::%(message)s"
message_privacy = true
