name: pr_tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    name: pytest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r dev_requirements.txt
        pip install -e .
    - name: Run tests and collect coverage
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 20
        max_attempts: 3
        retry_on: error
        command: pytest --cov=src/ --cov-config=.coveragerc --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
